[load_balancer]
listen_port = 8080
strategy = "RoundRobin"
# strategy = "LeastConnection"
queue_depth = 1024       # io_uring submission queue size
# max_connections = 10000 # yet to be implemented

[health_check] # yet to be implemented
path = "/health"
interval = 10

[[servers]]
name = "Server 1"
url = "http://127.0.0.1:8081"
connections = 200

[[servers]]
name = "Server 2"
url = "http://127.0.0.1:8082"
connections = 200
